# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build electron releases

on:
  push:
    branches: [ "master" ]
    tags-ignore: [ "v*" ]
  pull_request:
    branches: [ "master" ]

env:
  ADBLOCK: true

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        version: 8
        run_install: false
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Build/release Electron app
      uses: paneron/action-electron-builder@v1.8.1
      with:
        github_token: ${{ secrets.github_token }}
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        build_script_name: build-ci
        package_manager: pnpm
        skip_package_manager_install: true